### ISSUE TITLE
File broken when sync happens during download

### ISSUE THREAD

**Issue by Lapin-Blanc** [deajan/osync#147]
Hi,
I came across this issue following those steps :
1 : Start the download of a CentOS image on initiator : `wget http://mirror.kinamo.be/centos/7/isos/x86_64/CentOS-7-x86_64-NetInstall-1804.iso`

2 : During the download, a sync took place, thus only synchronizing par of the downloading file : ` osync.sh --initiator=/home/users/ --target=ssh://root@hole2.wonderland.infra//home/users/ --rsakey=~/.ssh/osync_rsa`

3 : Here is the stat of the partial file after partial sync on target : 
```
  Fichier : « CentOS-7-x86_64-NetInstall-1804.iso »
   Taille : 108817120   Blocs : 212536     Blocs d'E/S : 4096   fichier
Périphérique : 803h/2051d       Inœud : 9128764     Liens : 1
Accès : (0660/-rw-rw----)  UID : (    0/    root)   GID : (    0/    root)
 Accès : 2018-06-01 08:20:42.833774750 +0200
Modif. : 2018-06-01 08:20:30.742223497 +0200
Changt : 2018-06-01 08:20:42.833774750 +0200
  Créé : -
```
Note Modif. time, established at sync time

4 : Download ended on initiator : 
```
  Fichier : « CentOS-7-x86_64-NetInstall-1804.iso »
   Taille : 519045120   Blocs : 1013760    Blocs d'E/S : 4096   fichier
Périphérique : 803h/2051d       Inœud : 9293011     Liens : 1
Accès : (0660/-rw-rw----)  UID : (    0/    root)   GID : (    0/    root)
 Accès : 2018-06-01 08:21:15.000000000 +0200
Modif. : 2018-05-03 22:34:18.000000000 +0200
Changt : 2018-06-01 08:21:15.486801142 +0200
  Créé : -
```
Note that now that dowload has finished, Modif. time has changed reflecting the actual Modif. time of the original downloaded file.

5 : New sync at this moment results in full downloaded file on initiator getting overwritten by the partial one on remote...
```
  Fichier : « CentOS-7-x86_64-NetInstall-1804.iso »
   Taille : 108817120   Blocs : 212536     Blocs d'E/S : 4096   fichier
Périphérique : 803h/2051d       Inœud : 9293229     Liens : 1
Accès : (0660/-rw-rw----)  UID : (    0/    root)   GID : (    0/    root)
 Accès : 2018-06-01 08:23:27.398502884 +0200
Modif. : 2018-06-01 08:20:30.742223497 +0200
Changt : 2018-06-01 08:23:27.398502884 +0200
  Créé : -

```
So guess the problem comes from Modif. time, being actual during download and getting back in time after its end.

Btw, i'm wondering if there is a way to achieve only one way sync, initiator to target, overcome this issue ?

Cheers,

Fabien

**Comment by deajan** [comment]
Nice catch, but this is actually a normal behavior by design.
As wget / curl writes to a file, the modification timestamp gets updated continously.
Since rsync will base itself on mtime to check whether a file is newer, there's nothing you can do about that issue but downloading the file with rsync, as the latter will create a temporary filename while downloading, prevening the overwrite issue.

You may also use ```wget someURL -O output.tmp && mv output.tmp output``` in order to prevent the issue.

As for your question about one way sync, I think a simple rsync is a good pne way sync candidate.
I could indeed add some option like --sync=bidirectional|initiator2target|target2initiator to keep all the benefits of osync as wrapper for rsync.
