### ISSUE TITLE
"Cannot get value for [VERSION] in config file [/etc/os-release]" on Manjaro

### ISSUE THREAD

**Issue by guzzisti** [deajan/osync#190]
**Describe the bug**
When running osync.sh, the first message in the log is 
`Cannot get value for [VERSION] in config file [/etc/os-release]`

Although the job processing itself is successfull, the summary reports on error:
`osync finished with errors.`

**To Reproduce**
This happens when osync.sh is used on Manjaro Linux which is Arch-based and therefor a rolling-release distro. They only use version for their iso-releases, but have no version mentioned in `/etc/os-release`.
This may be the same with ArchLinux itself and other arch-based distro, though i haven't checked.

**Expected behavior**
The os-detection is ok without a VERSION mentioned in `/etc/os-release`.

**Desktop (please complete the following information):**
 - OS: Manjaro Mate
 - Bitness: amd64
 - Shell: bash

**Comment by deajan** [comment]
Known issue with osync v1.2.
Please use current git master, it's pretty safe to use.

**Comment by guzzisti** [comment]
I just tried the latest version from master, but the error is still there. I guess this line is the culprit: 
https://github.com/deajan/osync/blob/98c1b97fb033abe0721302f8c3e7b1fed839190c/osync.sh#L1432 
Additionally i needed to adjust the install.sh a bit to make it work again with the AUR PKGBUILD:
- The detection of systemd is changed to the official way which is mentioned in the manpage of `sd_booted`: https://github.com/guzzisti/osync/commit/35a7cb0b903e16cc6a199386ff546b3c8d248937
- The fakeroot env var was cleared, i'm not sure if this is intentionally but it broke the AUR package: https://github.com/guzzisti/osync/commit/1918c17e0959884ed4902dfc21e9783d881c0d3b

I create a PR if you are interested.

**Comment by deajan** [comment]
Ohh I see, I left the message as INFO instead of ERROR in function GetConfFileValue.
I'll change it to "No Version info found in os-release" so it's less threatening.
Is that okay for you ?

Also, I don't officially support PKGBUILD, I had @Shadowigor done that work for osync.
I'd indeed love any PR regarding this subject.

**Comment by Shadowigor** [comment]
I have not touched that PKGBUILD in years, it's definitely possible that it won't work anymore. But the `$FAKEROOT` variable is cleared because `install.sh` is generated from `dev/common_install.sh` and there it expects a `--prefix` argument if you want to use a fakeroot. Something along those lines, I'm really not sure anymore, it's been a while. But if you only change `install.sh`, it might get overwritten again at some point. You probably know more about the build process, though @deajan.

**Comment by guzzisti** [comment]
The PKGBUILD works fine for the stable-branch but does not work for the current master, thats why i had to touch things. The clearing of $FAKEROOT is not there in the old 1.2 install.sh.
But i need to touch it again anyway cause i missed that i need to update the files in `dev`.

**Comment by deajan** [comment]
@Shadowigor Thanks ;)
@guzzisti Please modify `common_install.sh` and have `install.sh` generated with `merge.sh`. From there, send the PR for `common_install.sh` which I can then merge into master.
That's a special workflow because it's a pain to get includes in bash.

**Comment by deajan** [comment]
@guzzisti Any news on this ?

**Comment by guzzisti** [comment]
Nope, sorry. The use case i intended to use osync for has changed a bit and i ended up using another tool. So i did not invest time to get the PKGBUILD work with the current master branch.

Maybe i can have a look again the next days but no promises made.

**Comment by victor-vc** [comment]
The same message "Cannot get value for [VERSION] in config file [/etc/os-release]." is shown on Gentoo, and it is right because the VERSION parameter is missing in that file.

/etc/os-release
> NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"

The Gentoo version is stored in /etc/gentoo-release though
`tr -d " [[:alpha:]]" </etc/gentoo-release`

**Comment by deajan** [comment]
Error is fixed for months in master. Can you confirm ?

**Comment by deajan** [comment]
That's more specific. I was searching for an error, not an actual log message.
I've pushed a fix in https://github.com/deajan/osync/commit/8e4e74542072a6e5da077369d9704d268f3e2a5e that makes this message a debug message.
