### ISSUE TITLE
Deleting large subfolder tree from target is slow

### ISSUE THREAD

**Issue by victor-vc** [deajan/osync#202]
I have a large folder tree that took around 9 min. for the initial sync. After that, the subsequent syncs take around 1 min. At some point I deleted one of the subfolders (around 1GB WordPress website). The sync after deleting this folder from initiator took around 10 mins.

You could easily reproduce this behavior by syncing a standard WordPress folder tree. After the initial sync, add a subfolder including the same standard WordPress folder tree. Run osync.sh for syncing the target. Remove the subfolder from initiator and run osync.sh again, and it should take longer than syncing the previously synced subfolder.

I don't know whether this is a bug or not, but I was expecting that deleting files/folders should be done quickly, since there is no file transfer between peers.

It is worth mentioning that in my configuration the deleted files are not kept (SOFT_DELETE=false), and the osync version used is the current git master (1.3.0-rc1).

**Comment by deajan** [comment]
So the actual problem is that deletion can't be handled by rsync.
Hence, the deletion processing is quite time consuming, having to deal file by file instead of batches.
There's nothing I could really do about this in the current osync implementation.

**Comment by victor-vc** [comment]
I don't now whether the rsync "--delete" options would be a feasible approach or not but I was expecting that deleting a folder from the initiator to be done on the target by simply deleting that specific folder, not by deleting its content file by file. Apart from that, osync is a great tool.

**Comment by deajan** [comment]
Early developpement of osync used `rsync --delete` which had to be replaced with a full blown deletion functionnality emulating soft deletes, because the rsync approach didn't allow only deletions to be propagated.
Using `--delete` switch while having main synchronisation ends up being stateless.
I've wrapped my head multiple times around a way to get rsync to do that job before writing extra code.

As for your remark on the current deletion process, see the inline comment :

```## On every run, check wheter the next item is already deleted because it is included in a directory already deleted```

This means that indeed we delete a folder with all it's content instead of deleting file per file basis, but we still need to parse the full deletion file since there might be out of tree files that need deletions.

**Comment by deajan** [comment]
I ran with _DEBUG=true _PERF_PROFILE=true and noticed that there isn't any particular slowdown on deletions.

``

**Comment by victor-vc** [comment]
I only tested it with the target folder on a remote machine. The results might be different on the same machine (same file system).

Steps to reproduce:

1. download drupal-9.0.1.tar.gz (17M size) to /tmp folder
2. uncompress the tar.gz archive
3. create config file: `INITIATOR_SYNC_DIR="/tmp/drupal-9.0.1"`, `TARGET_SYNC_DIR="ssh://target.host.com//tmp/drupal-9.0.1"`, `RSYNC_COMPRESS=false`, `SSH_COMPRESSION=false`, `SOFT_DELETE=false`
4. run the inital sync - took **11s** on Gbit connection `TIME: 11 - osync finished`
5. uncompress the tar.gz archive inside drupal-9.0.1 (creating the subfolder)
6. run osync again to sync the subfolder - took **11s** on Gbit connection `TIME: 11 - osync finished`
7. delete the drupal-9.0.1 subfolder from the initiator 
8. run osync again in order to delete the subfolder from target  - took **30s** on Gbit connection `TIME: 30 - osync finished`

Syncing (transferring from initiator to target) around 18.000 files (17MB) took 11s each time. Deleting the subfolder from initiator (containing the same 18.000 files), and syncing again (deleting from target) took **3 times longer**.

**Comment by deajan** [comment]
I ran some profiling on the code, and came to the conclusion that the deleted file list is the bottleneck.
It contains the deleted path plus all children paths, which it gives as argument to rsync which in turn takes 100% cpu to analyze the whole list.
The list could be optimized before passing it to rsync, so there would be less lost time processing it.

I have no quick idea that comes to my mind in order to optimize that list without wasting CPU time on the optimization, rendering the whole process useless, so I ended up asking that question on stackoverflow, see https://stackoverflow.com/questions/62652954/cleanup-a-path-list-in-bash-removing-all-children-paths-subdirectories

**Comment by deajan** [comment]
I've tinkered around with a simple fix for this.
In my tests, I got from 40 seconds to 5 seconds on the last run.

Would you mind trying out branch fast-deletion ?

**Comment by victor-vc** [comment]
It seems that the "slow deletion" issue is fixed in the _fast-deletion_ branch. I tested it in the same environment and got 10s `TIME: 10 - osync finished with warnings`, comparing to 30s (as I got with the master version).

**Comment by deajan** [comment]
Thanks for reporting back.
I still have to make a couple of detailed exclusion tests to validate this branch before I can merge this one back into master.
