### ISSUE TITLE
bash error on execution of osync.sh

### ISSUE THREAD

**Issue by nux1701** [deajan/osync#239]
**Describe the bug**
Execution of osync.sh from the master branch exits with error on line 2347.

**To Reproduce**
1. Run osync.sh from master branch

**Expected behavior**
Process should print help without error

** Deviated behavior**
Error : /usr/local/bin/osync.sh: line 2347: [: ==: unary operator expected prints

**Comment by deajan** [comment]
To be honest that's a bit empty as a bug report.
I just reviewed line 2347, and the variable that gets compared there gets initialized no matter what, so I don't really see the problem here.
Would you mind giving some more info please ?
Lile your environment and the way you run osync ?
Maybe even run `DEBUG=true osync.sh` and post its logs ?

**Comment by deajan** [comment]
My assumption is that the config file used by @nux1701 is an elder version that doesn't hold the "ALWAYS_SEND_MAILS" variable, hence producing the error.
The variable gets initialized only when no configuration file is used.

**Comment by jeremfg** [comment]
> My assumption is that the config file used by @nux1701 is an elder version that doesn't hold the "ALWAYS_SEND_MAILS" variable, hence producing the error. The variable gets initialized only when no configuration file is used.

That assumption makes a lot of sense, since this is my situation as well. I didn't think to check the new configuration file when upgrading from version 1.2

**Comment by deajan** [comment]
@jeremfg Please keep me updated
