### ISSUE TITLE
idea: "lite mode" for webdesigners who 90/95% of the time just update/append existing files

### ISSUE THREAD

**Issue by DrupaListo-com** [deajan/osync#57]
This idea means that I found myself constantly editing several files without the need osync to check local/remote deletion lists and free hdd space etc ...

...so if we could wrap each such operation in some if-clause ( = if ( ! $lite_mode ) ) we could skip those on purpose.

The cmdline option will be boolean - if it is given, its true, we skip, and if not given - we act as normal. Also a new var could be added in the config file.

This would be relatively easy I think to implement and will speed up drastically the program, making the UX for webdevs signifficantly better, as we do frequent little edits...

Questions/Opinions?

**Comment by deajan** [comment]
Sorry to ask, but why don't you just use a rsync -au if you only update files?

**Comment by deajan** [comment]
I could program that MINMUM_SPACE=0 would override testing disk space.
Also, not setting REMOTE_PING and REMOTE_3RD_PARTY_HOSTS would stop from doing pings.
SOFT_DELETE=no also increases speed.
Any other ideas ?

**Comment by DrupaListo-com** [comment]
you are right for rsync -au, its simply because I still haven't managed to read the rsync docs and test all the needed rsync options that would fix it for me... I always wanted a well tested rsync wrapper that "just works" , has a versatile config file and can do many features for me :)

**Comment by DrupaListo-com** [comment]
with bare rsync you always have the feeling you are missing some option ..

**Comment by DrupaListo-com** [comment]
I just found out I already use:

- MINIMUM_SPACE=0

- while my SOFT_DELETE_DAYS is not 0 but =30, which having no deleted files recently would not cause network traffic/ssh login slowdown right ?

- my CONFLICT_BACKUP_DAYS is also not 0 but 30 - same Q as above ...

- REMOTE_PING=no - this one seems to be REMOTE_HOST_PING on my config - did it change in newer commits ?

-  REMOTE_3RD_PARTY_HOSTS="" - this is empty here...


The only thing I am missing is some way to disable the deletion checks + remote/local deleted files listings... ... which would leave me only with a single or double rsync -av + some more options for hardlinks acl-s etc... ?? yes ?

**Comment by deajan** [comment]
MINIMUM_SPACE=0 only works with yesterday's commit on master branch.
SOFT_DELETE_DAYS not set to zero will trigger another ssh connection to the remote system.
The same applies with CONFLICT_BACKUP_DAYS.

Yep, I meant REMOTE_HOST_PING=no

REMOTE_3RD_PARTY_HOSTS="" will stop osync from trying to ping google or whatever to determine if the system has internet.

I'm sorry, but I won't add a deletion check skip option. This would go against a sync tool goal.
It would indeed leave you with a "protected" double rsync -av + options run.
Protected because there can't be concurrent runs. Protected because file attributes are synced both ways, where rsync would overwrite them with the latest run.

My parallelization work is almost over, it speeds up osync whenever the replicas have a lot of files because most actions that take time are done in background.

I'm thinking of adding parallel execution to some of the "core sync" functions. But there are many drawbacks:
- bandwidth limit won't work because of concurrent connections having each one it's own bandwidth limit
- resume system in case of failure will be harder to maintain
- Only a couple of functions can be parallelized (tree_list, delete_list and deletion_propagation).

**Comment by DrupaListo-com** [comment]
I've created two config files - one optimized for speed (suitable for updates only mode aka lite mode) and the other - regular.

The only two differences are:
-CONFLICT_BACKUP_DAYS=30
+CONFLICT_BACKUP_DAYS=0

-SOFT_DELETE_DAYS=30
+SOFT_DELETE_DAYS=0


I am using each conf file with a wrapper:
---- osync-start:
#!/bin/bash
osync.sh .osync.conf --on-changes --verbose $@
----
and

--- osync-start-lite
#!/bin/bash
osync.sh .osync.lite.conf --on-changes --verbose $@
---

The differences in performance are negligible due to the slight changes.. but in future there might be more differences in options...

**Comment by DrupaListo-com** [comment]
These run with latest git commit osync.

In the end a 10s sync is not perfect but with not so frequent edits  its enough for me ... While with very frequent edits, a little wait is still ok.

**Comment by DrupaListo-com** [comment]
I was hoping  to convince you to add the lite mode option where people that would use it would be advised/warned properly that this is a shoot in the foot type of option which is basically a tiny wrapper to rsync -au run two times in 2 directions....

**Comment by deajan** [comment]
I've made some code simplifications that gained another 1-2 seconds on exec time today.
What exactly do you want the lite mode to suppress ? Remote deletions ? Deletion & backup folder cleanup ? Attributes sync ?

**Comment by deajan** [comment]
Attributes sync can be disabled.
The quickest execution you can get is with the latest osync commit is 6 seconds instead of 12-13 seconds on remote sync.
```
MINIMUM_SPACE=0 PRESERVE_PERMISSIONS=no PRESERVE_OWNER=no PRESERVE_GROUP=no PRESERVE_EXECUTABILITY=no SOFT_DELETE_DAYS=0 CONFLICT_BACKUP_DAYS=0 REMOTE_PING=no ./n_osync.sh --initiator=/tmp/d1 --target=/tmp/d2
```

Still with this build, syncing is still two way with deletion support.

**Comment by deajan** [comment]
Quickest speed atained without sacrifying functionality in v1.2-beta. Closing this issue.
