### ISSUE TITLE
Fix systemd for CentOS 7

### ISSUE THREAD

**Issue by liger1978** [deajan/osync#92]
- Looking for binary in wrong place
 - Append ".conf" to instance name
 - Allow "2" as acceptable exit code. 

Will put in pull request

**Comment by deajan** [comment]
Nope, the bin dir will stay /usr/local/bin. Actually the RPM file would need a fix.
Why do you want to append ".conf" ? The instance name is basically the conf file name which already ends with ".conf".

Exit code 2 for warnings can be a valid exit code indeed.

**Comment by liger1978** [comment]
> Nope, the bin dir will stay /usr/local/bin. Actually the RPM file would need a fix.

Current spec file places binary in `/usr/bin` (well it did when I used `rpmbuild` on unmodified CentOS 7 system), so systemd service file fails to start.  Additionally if you're packaging for other people, I'd suggest you don't put stuff in `/usr/local`.  See for example Fedora Packaging Guidelines: https://fedoraproject.org/wiki/Packaging:Guidelines#No_Files_or_Directories_under_.2Fsrv.2C_.2Fusr.2Flocal.2C_or_.2Fhome.2F.24USER

> Why do you want to append ".conf" ?

Feel it is friendlier to type `systemctl start osync-srv@web_site` than `systemctl start osync-srv@web_site.conf` and this seems to match the convention of other multi-instance daemons in CentOS.  Doesn't matter that much.

**Comment by deajan** [comment]
While I do agree about following guidelines, osync has been historically installed into /usr/local/bin and I cannot simply change that after three release candidates and so close to a final release.

Also, using /usr/local/bin is convenient since osync is sometimes autogenerated.

A workaround would be to leave classic osync install.sh file use /usr/local/bin, and rpm file use {_bindir} that points to /usr/bin. There will have to be different service files depending on the setup method.

**Comment by deajan** [comment]
Exit codes updated and looking for the right binary place using which.
Thanks.

**Comment by deajan** [comment]
ExitCode 2 has been added to unit files.
Bin path is changed on the fly for RPM files.
The only thing I can't change is the syntax because of the already existing install base.

Thanks.
