### ISSUE TITLE
List or notification of conflicts

### ISSUE THREAD

**Issue by lifepillar** [deajan/osync#99]
Is it possible to get a list of the conflicts encountered during a sync run? If so, how?

**Comment by deajan** [comment]
There's no easy way to get this info since rsync doesn't give any additional info when doing backups.
The quick and dirty way is to identify files in the backup dirs with corresponding to the time of osync execution, example:
```find replica/.osync_dir/backups -type f -cnewer "2017-05-25 00:00:00" ! -cnewer "2017-05-25 23:59:59"```

I could also add a specific constant timestamp suffix for each conflict backed up file per run. What do you think about this solution ?

**Comment by lifepillar** [comment]
Well, I can't really judge, because I am not familiar with osync's internals. Is there any documentation on how osync handles conflicts (for example, how does it decide when to backup a file), or should I refer to the source code?

**Comment by deajan** [comment]
There's the documentation here http://netpower.fr/sites/default/files/soft/pdf-doc/osync_v1.2.pdf

I am asking more from functional point of view. What solution would fit best ?
Just a list of files that have been backed up ? Identifying each file in the backup directories with a suffix ?

**Comment by lifepillar** [comment]
>There's the documentation here

Thanks, for some reason it had escaped my notice. I'll report my feedback after reading it.

**Comment by lifepillar** [comment]
>The quick and dirty way is to identify files in the backup dirs with corresponding to the time of osync execution

This would give a list of *all* the files that were updated in each replica, not only the *conflicting* files, right? To be clear, by “conflict” I mean a file that is independently modified in both replicas between two osync runs.

It seems to me that, if I first sync two replicas, then change file `x` in replica one, then sync again, I will find a backup of `x` in replica two's backup folder, although this is not a conflict in the sense above.

**Comment by deajan** [comment]
> This would give a list of all the files that were updated in each replica, not only the conflicting files, right?
Nope, it's about identifying all files in the backup dirs, not the whole replicas.

osync is a stateful sync system. So it doesn't really care what happens between two runs.
Strictly speaking, osync considers a conflict everytime two identical filenames are found on each replica with different content, whether they were different before or not.

So identifying the backed-up files would be identifying all files that were updated instead of created, because of the statefulness.

**Comment by lifepillar** [comment]
Thanks for the explanation, now I have a much clearer understanding of how osync works. In fact, my original question was specifically about detecting files that are modified on both sides. For instance, consider this workflow (assume that replica one contains files `x` and `y`):

1. Replica one and replica two are synchronized.
2. File `y` is updated in replica one.
3. Files `x` and `y` are updated in replica two.
1. Replica one and replica two are synchronized again.

I see that osync technically does not cause any loss of information, because both `x` and `y` are backed up in replica one. But, the update at step (2) has been overwritten without ever being seen by replica two. Those are the situations that for me are critical to detect. If I understand correctly, osync cannot distinguish a “safe” update (`x`) from an “unsafe” update (`y`).

Anyway, to identify updated files, I think that running osync with `--verbose` is enough, because `--verbose` print rsync's “itemized” changes.

**Comment by deajan** [comment]
You won't be able to know what files are "unsafe" updates like you want with --verbose.
Btw, consider replacing ```--verbose``` with ```--summary --errors-only``` which is easier to read.

Give me some time so I can think of a way to detect "unsafe" changes without having to reprogram everything (I think I can easily compare tree lists in order to get that info).

**Comment by deajan** [comment]
osync creates a list of ctime and mtimes for each file in order to properly propagate ACLs.
I could keep those lists from previous runs, and compare current and previous lists to see if a file have been updated. If both files have been updated, the conflict resolution still happens automatically, but I can output which files had an "unsafe" update.
Would this fit to your needs ?

The required functional changes aren't that high.
I must just think of an error resuming process that would keep the previous run files until current run is finished in order to keep logs "real".

**Comment by deajan** [comment]
Began forking what will become v1.2.1 in order to introduce this feature.
I am thinking of another parameter allowing to send a special mail on "unsafe" conflict file presence.
Do you see any other conflict related options that could be useful ?
As of today, files with the exact same timestamp will be overwritten by the preferred replica.
Maybe another option to prefer a replica in case of an unsafe conflict ? Any other nice option you can think of ?

**Comment by lifepillar** [comment]
>If both files have been updated, the conflict resolution still happens automatically, but I can output which files had an "unsafe" update. Would this fit to your needs ?

Yes, this is exactly what I'd like to see. Getting an email when such updates are detected would be wonderful. I don't think that other options are necessary.

**Comment by deajan** [comment]
Got the ```--log-conflicts``` to work today.
Still some programming to do in error handling and code cleanup, but basics work.
Care for a test run ?

**Comment by deajan** [comment]
Finished adding the conflict list detection on master branch.
New options are ```--log-conflicts``` and ```--alert-conflicts``` and their counterparts in configuration files.

Does this fit your needs ?

**Comment by lifepillar** [comment]
I've tested `--log-conflicts` briefly, and it seems to detect conflicts correctly. After running `osync` a few times, though, it has started to fail with `Cannot create conflict list file`. I don't know exactly why. Anyway, I'll test more thoroughly during the weekend.

**Comment by deajan** [comment]
Indeed I still need to write the unit tests for that function in order to release this branch which is still in developpment, and there's a major refactoring of the conflict code with the ACL sync code and preferred conflict update source that is postponed for v1.3.
In the meantime, I'd love to have your usecases where the conflict detection fails so I can harden the unit tests :)
